//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace laz { namespace TCDashboardInterface {

ref class TCDashboardInterfaceConsumer;

public ref class TCDashboardInterfaceGoFunkyResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool Success
    {
        bool get() { return m_interfaceMemberSuccess; }
    internal:
        void set(_In_ bool value) { m_interfaceMemberSuccess = value; }
    }
    
    static TCDashboardInterfaceGoFunkyResult^ CreateSuccessResult(_In_ bool interfaceMemberSuccess)
    {
        auto result = ref new TCDashboardInterfaceGoFunkyResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Success = interfaceMemberSuccess;
        return result;
    }
    
    static TCDashboardInterfaceGoFunkyResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TCDashboardInterfaceGoFunkyResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    bool m_interfaceMemberSuccess;
};

public ref class TCDashboardInterfaceGoBoringResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool Success
    {
        bool get() { return m_interfaceMemberSuccess; }
    internal:
        void set(_In_ bool value) { m_interfaceMemberSuccess = value; }
    }
    
    static TCDashboardInterfaceGoBoringResult^ CreateSuccessResult(_In_ bool interfaceMemberSuccess)
    {
        auto result = ref new TCDashboardInterfaceGoBoringResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Success = interfaceMemberSuccess;
        return result;
    }
    
    static TCDashboardInterfaceGoBoringResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TCDashboardInterfaceGoBoringResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    bool m_interfaceMemberSuccess;
};

public ref class TCDashboardInterfaceJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property TCDashboardInterfaceConsumer^ Consumer
    {
        TCDashboardInterfaceConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ TCDashboardInterfaceConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    TCDashboardInterfaceConsumer^ m_consumer;
};

} } } 
